### ISSUE TITLE
G29 wheel support?

### ISSUE THREAD

**Issue by deeph46** [lexfp/G25toPPM#1]
Hi,

I have tried assembly this. Instead using G25, I used G29. But I cant get it to work. My G29 give me initial boot, which calibration on power on. But I can't get PPM signal outputting from arduino.

Does this sketch will work on G29 wheel? and is it correct wired the digital pin 3 to PPM external module?

Thank you.

**Comment by lexfp** [comment]
Sorry, I don't have a G29 and so it is not supported.

**Comment by Lolig4** [comment]
@deeph46 you can try if my project works: https://github.com/Lolig4/T248-to-PPM

**Comment by deeph46** [comment]
Hi, does the ffb also works?

**Comment by Lolig4** [comment]
FFB limiting for the motion range and autocenter strength works, as do the statically configured rumble commands; however, they are not currently being used.

**Comment by Lolig4** [comment]
Which Arduino do you use?

**Comment by deeph46** [comment]
I used much for Arduino Pro Micro, but also UNO, Leonardo and Nano.

**Comment by Lolig4** [comment]
Which USB host shield do you have?

**Comment by Lolig4** [comment]
i have https://de.aliexpress.com/item/32817563853.html

**Comment by deeph46** [comment]
i have both, that smaller one and UNO size.

**Comment by Lolig4** [comment]
do you use a logic Level shifter?

**Comment by deeph46** [comment]
Sorry late reply, no I don't use any logic level shifter

**Comment by Lolig4** [comment]
This can be a problem because most of these USB host shields communicate with 3.3v and your Arduino runs with 5v.

**Comment by deeph46** [comment]
> [@deeph46](https://github.com/deeph46) you can try if my project works: https://github.com/Lolig4/T248-to-PPM

Hi, I tried to flash this. But got error, collect2.exe: error: id returned 1 exit status

Trying to flash Arduino ProMicro
